# Generated by Django 5.0.3 on 2025-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0005_rename_idfactura_codigoseguimiento_id_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
