# Generated by Django 5.0.3 on 2025-02-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0006_usuario_profile_completed_alter_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profile_completed',
        ),
    ]
